#ifndef MICRO_CONTROLLER_ELEVATOR_MINI_PROJECT_UTILITY_H
#define MICRO_CONTROLLER_ELEVATOR_MINI_PROJECT_UTILITY_H

#include "types.h"

int add_to_floor_queue(int floor);

#endif //MICRO_CONTROLLER_ELEVATOR_MINI_PROJECT_UTILITY_H
